# Site settings
title: Aidan Calderhead Portfolio
email: aidan.calderhead@gmail.com
description: "Portfolio showcasing professional, academic, and personal data projects, including my areas of research interest. This template was inspired by @archd3sai."
url: "https://acalderhead.github.io"

# Author
author:
  name: Aidan Calderhead
  email: aidan.calderhead@gmail.com

# Theme
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Defaults for posts/pages
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Aidan Calderhead"

# Build settings
markdown: kramdown
highlighter: rouge

# Minima theme options (optional)
minima:
  skin: dark
  accent: "10e8a4" # example accent color
